version: '3.8'

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8787:8787"  # Expose port 8787 for the Node.js app

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"  # Expose MySQL on port 3306