apiVersion: v1
kind: Pod

metadata:
  name: myhtmlapp
  labels:
    app: myhtmlapp
    tier: frontend
spec:
  containers:
    - name: myhtml-container
      image: satyabrataswain/myhtmlapp:latest # Placeholder, will be updated in the pipeline
      ports:
      - containerPort: 80
  imagePullSecrets:
    - name: myregistrykey
