apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  ports:
    - port: 8787
      targetPort: 8787
      nodePort: 30001   # You can specify the port you want to access externally.
  selector:
    app: nodejs-app